### ISSUE TITLE
H1 H2 H3 buttons does not toggle the style

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/publish#163]
You can't remove the heading style by clicking H1 button twice. The same for H2 and H3.
https://github.com/freeCodeCamp/publish/assets/25644062/165cc957-ae9d-4fe4-84db-1ce4e573331c

We should either:
- Make it toggle
- Add a button to clear all the style

**Comment by Sembauke** [comment]
Not sure if we can change this.
