### ISSUE TITLE
Hide Pages menu

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/publish#331]

**Comment by ojeytonwilliams** [comment]
@sidemt do you mind expanding a bit on why we're doing this?  As I recall from the meeting last week there was some discussion about the necessity of having pages be distinct from potsts. For one thing we discussed if pages should appear in a user's list of articles.

Regardless of what the rationale is, it would be good to have it documented.

**Comment by ojeytonwilliams** [comment]
Perfect, thanks for sharing that.
