### ISSUE TITLE
Markdown blocks in editor

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/publish#389]
This is based on feedback from Abbey.

> is there a way to insert a markdown block in the editor like how Ghost does? Again, lots of authors write in markdown and would want this. Allows for more specific manipulation like making multi-tiered lists, for example (like a numbered list with a bulleted list within it, if that makes sense).  

In Ghost, we can insert a markdown block like this:

![Image](https://github.com/freeCodeCamp/publish/assets/25644062/bd4da446-e9ad-4405-ba44-cff8b705003a)

It renders like this:

![Image](https://github.com/freeCodeCamp/publish/assets/25644062/b12d88d2-b0d4-4da7-af12-75c5b7dac10d)

**Comment by Sembauke** [comment]
Markdown blocks are the same as code blocks.

**Comment by Sembauke** [comment]
closed by #418

**Comment by Nirajn2311** [comment]
So this block would allow the authors to paste markdown which is then converted to HTML, right?

**Comment by Sembauke** [comment]
But the editor has all the functionality of markdown? The markdown always gets converted into HTML.

This is like adding another editor inside the editor.

**Comment by Nirajn2311** [comment]
I tried out the markdown block feature in Ghost which just basically makes a part of the editor into a markdown editor and that's like what Sem said, another editor inside the editor. Instead of doing this, why don't we show a toggle button that will let the author type in formatted text or raw Markdown.
